### ISSUE TITLE
Can we run this action against a different GHES server?

### ISSUE THREAD

**Issue by rajbos** [peter-murray/workflow-application-token-action#12]
Hi, I would like to run this action against a different GHES server to get an access token from it by using the GitHub Application. 

Is that possible?

I tried by overwriting the GITHUB_API_URL but I do not see that being picked up.

``` yaml
      - uses: peter-murray/workflow-application-token-action@v1.3.0
        name: Get acces token from App on ACC
        id: get_workflow_token
        env:
          GITHUB_API_URL: https://gh-server.com/api/v3
        with:
          application_id: ${{ env.GH_AUTOMATION_ID_ACC }}
          application_private_key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY_ACC }}
          organization: my-org
```  

CC @peter-murray
