### ISSUE TITLE
empty token

### ISSUE THREAD

**Issue by h2oearth** [peter-murray/workflow-application-token-action#43]
The job seems to work, but I have an empty token. I do not know why I endup with an empty token :-/.  Here is my code

```
permissions:
  actions: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  get-token:
    runs-on: ubuntu-latest
    outputs:
      github-token: ${{ steps.get_actions_token.outputs.token }}
    name: Update Apps
    steps:
      - name: Get Workflow Token
        id: get_actions_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          revoke_token: true
   use-token:
     name: MyWorkflow
     needs: get-token
     uses: mycompany/myrepo/.github/workflows/workflow.yml@master
     secrets:       
        GH_TOKEN: ${{ needs.get-token.outputs.github-token }}
```

output

```
Obtaining application installation for organization: myorganization
{"token":"***","expires_at":"2025-12-04T06:30:43Z","permissions":{"contents":"write","metadata":"read"},"repository_selection":"selected"}
Successfully generated an access token for application
```
